import * as SQLite from 'expo-sqlite';

// Member interface
export interface Member {
  id: number;
  name: string;
  initials: string;
  bio: string;
  events: string[];
}

// Initialize database
let db: SQLite.SQLiteDatabase | null = null;

export const initDatabase = async (): Promise<void> => {
  try {
    db = await SQLite.openDatabaseAsync('members.db');
    
    // Create tables
    await db.execAsync(`
      PRAGMA journal_mode = WAL;
      
      CREATE TABLE IF NOT EXISTS members (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        initials TEXT NOT NULL,
        bio TEXT NOT NULL
      );
      
      CREATE TABLE IF NOT EXISTS events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE
      );
      
      CREATE TABLE IF NOT EXISTS member_events (
        member_id INTEGER,
        event_id INTEGER,
        FOREIGN KEY (member_id) REFERENCES members (id),
        FOREIGN KEY (event_id) REFERENCES events (id),
        PRIMARY KEY (member_id, event_id)
      );
    `);

    // Check if data already exists
    const result = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) as count FROM members');
    
    if (result && result.count === 0) {
      await seedDatabase();
    }
  } catch (error) {
    console.error('Error initializing database:', error);
  }
};

// Seed database with all members and events
const seedDatabase = async (): Promise<void> => {
  if (!db) return;

  const membersData = [
    { name: 'Ashrit Kopparthi', bio: 'Passionate about finance and international business strategy.' },
    { name: 'Ian Mendonca', bio: 'Tech enthusiast with a love for problem-solving.' },
    { name: 'Aayush Pant', bio: 'Coding wizard and competitive programming champion.' },
    { name: 'Atiksh Matharu', bio: 'Detail-oriented and always ready for a challenge.' },
    { name: 'Liam Chang', bio: 'Team player with strong analytical skills.' },
    { name: 'Rohaan Pasha', bio: 'Finance geek who loves crunching numbers.' },
    { name: 'Sacchit Boddapati', bio: 'Data science enthusiast and AI explorer.' },
    { name: 'Gautham Manigantan', bio: 'Full-stack developer with a creative edge.' },
    { name: 'Niya Aslam', bio: 'Marketing maven with a flair for creativity.' },
    { name: 'Deethya Anuga', bio: 'Ambitious entrepreneur with big ideas.' },
    { name: 'Lucky Kadiam', bio: 'Sales expert who loves connecting with people.' },
    { name: 'Vienna Shin', bio: 'Strategic thinker with a passion for advertising.' },
    { name: 'Olivia Shin', bio: 'Creative mind always looking for the next big thing.' },
    { name: 'Naman Agrawal', bio: 'Tech support guru and problem solver.' },
    { name: 'Sprihi Sharma', bio: 'Agribusiness advocate and sustainability champion.' },
    { name: 'Gabrielle Quiere', bio: 'Organized leader with a knack for planning.' },
    { name: 'Ashmi Shah', bio: 'Healthcare enthusiast dedicated to making a difference.' },
    { name: 'Samhitha Manukonda', bio: 'Banking expert with a strategic mindset.' },
    { name: 'Aman Kolli', bio: 'Finance whiz with entrepreneurial spirit.' },
    { name: 'Saipranav Rebala', bio: 'Supply chain strategist and logistics pro.' },
    { name: 'Brandon Osckar', bio: 'Personal finance advocate helping others succeed.' },
    { name: 'Sameer Hussaini', bio: 'Risk management specialist with sharp instincts.' },
    { name: 'Shaurya Bansal', bio: 'Broadcast journalist with a voice for change.' },
    { name: 'Arush Rasure', bio: 'Business law enthusiast and debate champion.' },
    { name: 'Shikha Prajapati', bio: 'Future educator inspiring the next generation.' },
    { name: 'Niteesh AJ', bio: 'Media producer with a passion for storytelling.' },
    { name: 'Aashi Patel', bio: 'Parliamentary procedure expert and leader.' },
    { name: 'Shriya Aroun', bio: 'Team collaborator with excellent communication skills.' },
    { name: 'Rachel So', bio: 'Organized and detail-focused project manager.' },
    { name: 'Anoushka Haloi', bio: 'Public service advocate making an impact.' },
    { name: 'Natalie Ho', bio: 'Event planner extraordinaire with creative vision.' },
    { name: 'Saranya Potukuchi', bio: 'Visual designer bringing ideas to life.' },
    { name: 'Varalika Konduri', bio: 'Broadcast journalist covering the latest news.' },
    { name: 'Saiprajna Ravooru', bio: 'Public speaker inspiring audiences everywhere.' },
    { name: 'Shrita Kopparthi', bio: 'Business communicator with persuasive skills.' },
    { name: 'Ved Dalvi', bio: 'Business procedures expert and efficiency guru.' },
    { name: 'Varun Patwardhan', bio: 'Broadcast journalist with investigative skills.' },
    { name: 'Rafail Popa', bio: 'Business management strategist and innovator.' },
    { name: 'Khushi Bhimani', bio: 'Job interview coach helping others shine.' },
    { name: 'Anna Abraham', bio: 'Financial planner with a heart for helping others.' },
    { name: 'Kriyan Krishnan', bio: 'Digital video producer and creative storyteller.' },
    { name: 'Sahana Singh', bio: 'Retail management expert with customer focus.' },
    { name: 'Rohil Varshney', bio: 'Digital content creator and video editor.' },
    { name: 'Iman Siddiqui', bio: 'Sales presentation pro with charisma.' },
    { name: 'Nitya Anand', bio: 'Journalism enthusiast uncovering the truth.' },
    { name: 'Amr Omar', bio: 'Business ethics advocate for corporate responsibility.' },
    { name: 'Muhammad Koul', bio: 'Ethical business leader with strong values.' },
    { name: 'Adam Alaruri', bio: 'Healthcare administrator improving patient care.' },
    { name: 'Kashvi Arora', bio: 'Organizational leader driving team success.' },
    { name: 'Ananya Mallick', bio: 'Event planner creating unforgettable experiences.' },
    { name: 'Shrita Palla', bio: 'Business law scholar and advocate.' },
    { name: 'Snigdha Sri Garlapati', bio: 'Financial analyst with sharp insights.' },
    { name: 'Ellisandra Sou', bio: 'Business ethics champion for transparency.' },
    { name: 'Tanvi Kuttuva', bio: 'Intro to business communication rising star.' },
    { name: 'Aashini Ramesh', bio: 'Business ethics researcher and writer.' },
    { name: 'Swarali Karale', bio: 'Website designer crafting beautiful experiences.' },
    { name: 'Srianvika Siram', bio: 'Business plan strategist and entrepreneur.' },
    { name: 'Puranjay Wadhawan', bio: 'Business law expert and legal scholar.' },
    { name: 'Gayathri Priya Balla', bio: 'Journalism advocate for truth and justice.' },
    { name: 'Swati Premkumar', bio: 'Business law researcher and policy analyst.' },
    { name: 'Saanvi Lankalapalli', bio: 'Parliamentary procedure specialist.' },
    { name: 'Aahna Dattkaya', bio: 'Retail merchandising expert with style.' },
    { name: 'Ayla Tamber', bio: 'Event planner and business management leader.' },
    { name: 'Keerth Kotha', bio: 'Intro to business concepts enthusiast.' },
    { name: 'Amogh Jain', bio: 'Website design innovator and creative thinker.' },
    { name: 'Rajeev Kalagara', bio: 'Business management strategist.' },
    { name: 'Nella Sharma', bio: 'Customer service champion with empathy.' },
    { name: 'Amreen Dadwal', bio: 'Real estate investor and market analyst.' },
    { name: 'Elizabeth Tselyuk', bio: 'Intro to business presentation leader.' },
    { name: 'Sashvitha Poobalan', bio: 'Social media strategist and content creator.' },
    { name: 'Isabella Salazar', bio: 'Social media expert building online communities.' },
    { name: 'Abhi Kaki', bio: 'Business management innovator.' },
    { name: 'Hei kan Tang', bio: 'Business management team player.' },
    { name: 'Arnav Verma', bio: 'Business management problem solver.' },
    { name: 'Vihaan Singh', bio: 'Data analysis expert and business planner.' },
    { name: 'Ruhaan Sidhu', bio: 'Business plan strategist with vision.' },
    { name: 'Rayan Alam', bio: 'Website coding developer and tech innovator.' },
    { name: 'Anushree Gupta', bio: 'Social media strategist and business planner.' },
    { name: 'Vilina Pai', bio: 'Human resources advocate for workplace culture.' },
    { name: 'Tanisha Chandel', bio: 'Graphic designer with artistic vision.' },
    { name: 'Tanishka Yella', bio: 'Business plan creator and graphic designer.' },
    { name: 'Avantika Santhosh', bio: 'Business plan collaborator and strategist.' },
    { name: 'Prisha Sharma', bio: 'Data science enthusiast and business planner.' },
    { name: 'Ayush Balwalli', bio: 'Sports management expert and team leader.' },
    { name: 'Kailani Fisher', bio: 'Sports and entertainment strategist.' },
    { name: 'Shahaan Dhebar', bio: 'Entrepreneurship advocate and business planner.' },
    { name: 'Aaric Das', bio: 'Business plan innovator with fresh ideas.' },
    { name: 'Aarav Verma', bio: 'Business plan strategist and visionary.' },
    { name: 'Satvik Tadiparti', bio: 'Retail merchandising expert and business planner.' },
    { name: 'Sneha Nandkeolyar', bio: 'Career portfolio builder and entrepreneur.' },
    { name: 'Geethika Chandolu', bio: 'Social media strategist and career planner.' },
    { name: 'Saswathy Srishankar', bio: 'Job interview expert and career coach.' },
    { name: 'Jahnavi Shukla', bio: 'Career portfolio specialist.' },
    { name: 'Ali Mirza', bio: 'Intro to public speaking champion and career builder.' },
    { name: 'Alisa Kyrychenko', bio: 'Website coding developer and career planner.' },
    { name: 'Aadit Aggarwal', bio: 'Mobile app developer and coding expert.' },
    { name: 'Rithvika Devisetti', bio: 'Website coding developer and programmer.' },
    { name: 'Sayesha Rajbhandari', bio: 'Coding and programming specialist.' },
    { name: 'Gagana Rudra Bodala', bio: 'Website coding developer and innovator.' },
    { name: 'Matthew Kokhan', bio: 'Graphic designer and game programming expert.' },
    { name: 'Eric Luo', bio: 'Graphic designer and game developer.' },
    { name: 'Srivats Iyer', bio: 'Computer game programming specialist.' },
    { name: 'Aryaman Rao', bio: 'Supply chain strategist and game developer.' },
    { name: 'Abhinav Iyer', bio: 'Insurance expert and game programmer.' },
    { name: 'Dhanuh Bogam', bio: 'Cybersecurity specialist and game developer.' },
    { name: 'Elina Shah', bio: 'Intro to programming expert and game developer.' },
    { name: 'Ashrita Saravanan Vaishnavi', bio: 'Cybersecurity analyst and game programmer.' },
    { name: 'Sarthak Kansal', bio: 'Computer applications expert and intro to business communicator.' },
    { name: 'Riddhesh Jaini', bio: 'Computer applications specialist and supply chain analyst.' },
    { name: 'Anvi Dua', bio: 'Computer applications expert and website coder.' },
    { name: 'Aishwarya Kumaran', bio: 'Computer problem solver and website developer.' },
    { name: 'Mahima Iyer', bio: 'Computer problem solver and future business leader.' },
    { name: 'Shubh Parihar', bio: 'Computer problem solver and data science enthusiast.' },
    { name: 'Akshar Parmar', bio: 'Computer problem solver and website designer.' },
    { name: 'Aditi Kesarwani', bio: 'Computer problem solver and event planner.' },
    { name: 'Ryan Cutinha', bio: 'Networking infrastructures expert and problem solver.' },
    { name: 'Ryan Wang', bio: 'Mobile app developer and computer problem solver.' },
    { name: 'Meera Bhise', bio: 'Customer service expert and sports management leader.' },
    { name: 'Maitree Chauhan', bio: 'Customer service champion and human resources advocate.' },
    { name: 'Megan Song', bio: 'Customer service specialist and marketing expert.' },
    { name: 'Sarah Chung', bio: 'Customer service pro and impromptu speaker.' },
    { name: 'Krish Shah', bio: 'Customer service leader and intro to marketing expert.' },
    { name: 'Aanya Sheth', bio: 'Customer service specialist and event planner.' },
    { name: 'Feven Bizuayehu', bio: 'Cybersecurity expert and data analyst.' },
    { name: 'Yusuf Abbasi', bio: 'Cybersecurity specialist and website designer.' },
    { name: 'Ayla Mir', bio: 'Cybersecurity analyst and data analyst.' },
    { name: 'Adyan Ali', bio: 'Cybersecurity expert and sales presenter.' },
    { name: 'Mikul Pasupathi', bio: 'Cybersecurity specialist and intro to business presenter.' },
    { name: 'Vivaan Pole', bio: 'Cybersecurity analyst and intro to social media strategist.' },
    { name: 'Yuvin Agrawal', bio: 'Cybersecurity expert and data science enthusiast.' },
    { name: 'Shaurya Gera', bio: 'Data analyst and data science expert.' },
    { name: 'Sreshta Namala', bio: 'Data analyst and public speaker.' },
    { name: 'Vanshika Kalluri', bio: 'Data analyst and hospitality management expert.' },
    { name: 'Nishtha Priya', bio: 'Data analyst and networking infrastructures specialist.' },
    { name: 'Pushkal Kumar', bio: 'Data analyst and mobile app developer.' },
    { name: 'Guhan Thiagarajan', bio: 'Data analyst and networking expert.' },
    { name: 'Sujan Saravanan', bio: 'Data analyst and intro to business presenter.' },
    { name: 'Sidharth Vellanki', bio: 'Data analyst and network design expert.' },
    { name: 'Abhinav Bonagiri', bio: 'Data analyst and network designer.' },
    { name: 'Saravana Jayavelu', bio: 'Data analyst and sports management strategist.' },
    { name: 'Venkat Chandra', bio: 'Data analyst and future business leader.' },
    { name: 'Neel Patel', bio: 'Data analyst and future business leader.' },
    { name: 'Fiona Au', bio: 'Data analyst and public service announcer.' },
    { name: 'Ronit Agarwal', bio: 'Data science expert and website coder.' },
    { name: 'Satya Tumuluri', bio: 'Data science specialist and economics expert.' },
    { name: 'Vyom Joshi', bio: 'Data science enthusiast and financial planner.' },
    { name: 'Vidhyuth Rajesh Kanna', bio: 'Data science expert and economics analyst.' },
    { name: 'Shreya Battula', bio: 'Data science specialist and intro to programmer.' },
    { name: 'Shaaz Alicherry', bio: 'Data science expert and international business strategist.' },
    { name: 'Devansh Ahuja', bio: 'Data science enthusiast and intro to business presenter.' },
    { name: 'Rithwik Bhimanadhuni', bio: 'Data science expert and digital video producer.' },
    { name: 'Gyandeep Kintali', bio: 'Data science specialist and analyst.' },
    { name: 'Avisha Agrawal', bio: 'Digital animator and intro to IT expert.' },
    { name: 'Disha Pudakar', bio: 'Digital animator and creative designer.' },
    { name: 'Saisha Agarwal', bio: 'Digital animator and parliamentary procedure specialist.' },
    { name: 'Oviya Raja', bio: 'Digital animator and healthcare administrator.' },
    { name: 'Arian Khaire', bio: 'Digital animator and sports management expert.' },
    { name: 'Krishna Chintalapati', bio: 'Digital animator and hospitality management specialist.' },
    { name: 'Mikail Ahmed', bio: 'Digital animator and personal finance expert.' },
    { name: 'Ishaan Agarwal', bio: 'Digital animator and website designer.' },
    { name: 'Kavya Subramanian', bio: 'Digital video producer and sales presenter.' },
    { name: 'tarinika prasath', bio: 'Digital video producer and securities analyst.' },
    { name: 'Saptaparna Dey', bio: 'Digital video producer and creative storyteller.' },
    { name: 'Joel Bijoy', bio: 'Digital video producer and website coder.' },
    { name: 'Rishik Birru', bio: 'Digital video producer and website coder.' },
    { name: 'Pranav Saravanan', bio: 'Digital video producer and financial analyst.' },
    { name: 'Benjamin Xavier', bio: 'Digital video producer and future educator.' },
    { name: 'Marcus Balauag', bio: 'Digital video producer and financial analyst.' },
    { name: 'Keyan Shah', bio: 'Digital video producer and mobile app developer.' },
    { name: 'Aadhav Iyer', bio: 'Digital video producer and content creator.' },
    { name: 'Max Trepp', bio: 'Digital video producer and media specialist.' },
    { name: 'Pratyush Patnaik', bio: 'Digital video producer and insurance expert.' },
    { name: 'Tasmia Minhaz', bio: 'Economics expert and graphic designer.' },
    { name: 'Anisha Datta', bio: 'Economics analyst and financial statement expert.' },
    { name: 'Rayan Aziz', bio: 'Economics specialist and personal finance advocate.' },
    { name: 'Nathan Dusapin', bio: 'Economics expert and personal finance pro.' },
    { name: 'Saahithi Mamillapalli', bio: 'Entrepreneurship advocate and marketing expert.' },
    { name: 'Julian Sieu', bio: 'Entrepreneurship strategist and sales presenter.' },
    { name: 'Ajay Joshi', bio: 'Entrepreneurship expert and parliamentary procedure specialist.' },
    { name: 'Aniruddh Gatla', bio: 'Entrepreneurship advocate and international business strategist.' },
    { name: 'Om Kharade', bio: 'Entrepreneurship expert and intro to business presenter.' },
    { name: 'Kobee Tan', bio: 'Entrepreneurship strategist and innovator.' },
    { name: 'Elisha Kim', bio: 'Event planner and intro to marketing expert.' },
    { name: 'Sabrina Castellanos French', bio: 'Event planner and organizer extraordinaire.' },
    { name: 'Sinchana Vivek', bio: 'Event planner and sales presenter.' },
    { name: 'Dhatri Achyutha', bio: 'Event planner and healthcare administrator.' },
    { name: 'Nayana Surisetti', bio: 'Event planner and intro to social media strategist.' },
    { name: 'Varenya Pothukuchi', bio: 'Event planner and visual designer.' },
    { name: 'Yasha Gatla', bio: 'Event planner and international business expert.' },
    { name: 'Srianshi Samantaray', bio: 'Event planner and financial planner.' },
    { name: 'Rithika Pooboni', bio: 'Event planner and graphic designer.' },
    { name: 'Quinlan Pradana', bio: 'Event planner and organizer.' },
    { name: 'Aarav Patil', bio: 'Event planner and sports management expert.' },
    { name: 'Vamika Putane', bio: 'Event planner and organizer.' },
    { name: 'Samvit Nadgouda', bio: 'Event planner and intro to FBLA expert.' },
    { name: 'Aileen Putla', bio: 'Event planner and website designer.' },
    { name: 'Ritul Dwivedi', bio: 'Event planner and public speaker.' },
    { name: 'Sahana Senthilkumar', bio: 'Event planner and visual designer.' },
    { name: 'Angelika Prabhu', bio: 'Event planner and visual designer.' },
    { name: 'Sarah John', bio: 'Event planner and social media strategist.' },
    { name: 'Andrea Chalissery', bio: 'Event planner and intro to business concepts expert.' },
    { name: 'Komalika Mamidi', bio: 'Financial planner and intro to business presenter.' },
    { name: 'Nandini Komma', bio: 'Financial planner and intro to business presenter.' },
    { name: 'Samhitha Nekkanty', bio: 'Financial planner and social media strategist.' },
    { name: 'Joshita Munnangi', bio: 'Financial planner and social media strategist.' },
    { name: 'Anshi Mehta', bio: 'Financial planner and social media strategist.' },
    { name: 'Devansh Agarwal', bio: 'Financial planner and intro to programmer.' },
    { name: 'Aiden Sol', bio: 'Financial planner and social media strategist.' },
    { name: 'Nathan Son', bio: 'Financial planner and social media strategist.' },
    { name: 'Jeffrey Jiang', bio: 'Financial planner and personal finance expert.' },
    { name: 'Advaith Koushik', bio: 'Financial statement analyst and intro to programmer.' },
    { name: 'Anay Arya', bio: 'Financial statement analyst and network designer.' },
    { name: 'Nishad Satghare', bio: 'Financial statement analyst and network designer.' },
    { name: 'Matthew Song', bio: 'Financial statement analyst and network designer.' },
    { name: 'Jaithra Putane', bio: 'Financial statement analyst and public service announcer.' },
    { name: 'Sarayu Nukala', bio: 'Financial statement analyst and mobile app developer.' },
    { name: 'Sanskriti Shukla', bio: 'Financial statement analyst and public administration expert.' },
    { name: 'Anusha Date', bio: 'Financial statement analyst and supply chain manager.' },
    { name: 'Rishitha Sindogi', bio: 'Future business educator and parliamentary procedure expert.' },
    { name: 'Sara Kansal', bio: 'Future business educator and social media strategist.' },
    { name: 'Anaya Borade', bio: 'Future business educator and project manager.' },
    { name: 'Kelly Mascarenhas', bio: 'Future business educator and sports management expert.' },
    { name: 'Ishaan Regalla', bio: 'Future business leader and real estate expert.' },
    { name: 'Aradhna Praveen', bio: 'Future business leader and social media strategist.' },
    { name: 'Mahi Parikh', bio: 'Graphic designer and securities analyst.' },
    { name: 'Saanvi Vijayvargiya', bio: 'Graphic designer and visual designer.' },
    { name: 'Ananya Gupta', bio: 'Graphic designer and international business expert.' },
    { name: 'Tej Simha Tummapudi', bio: 'Graphic designer and website coder.' },
    { name: 'Kody Choi', bio: 'Graphic designer and public service announcer.' },
    { name: 'Gianna Canos', bio: 'Graphic designer and parliamentary procedure expert.' },
    { name: 'Sankari Kk', bio: 'Graphic designer and public speaker.' },
    { name: 'Ajooni Dhanoa', bio: 'Graphic designer and visual designer.' },
    { name: 'Andy Yang', bio: 'Graphic designer and website designer.' },
    { name: 'Soumil Pole', bio: 'Graphic designer and website designer.' },
    { name: 'Avni Panchal', bio: 'Graphic designer and visual designer.' },
    { name: 'Kavya Mohanasundaram', bio: 'Graphic designer and visual designer.' },
    { name: 'Yunhan Li', bio: 'Graphic designer and website designer.' },
    { name: 'Sanjana Krishnan', bio: 'Healthcare administrator and social media strategist.' },
    { name: 'Srinath Vemula', bio: 'Healthcare administrator and real estate expert.' },
    { name: 'Ellena Wong', bio: 'Healthcare administrator and human resources advocate.' },
    { name: 'Shravya More', bio: 'Healthcare administrator and social media strategist.' },
    { name: 'Laya Mohan', bio: 'Healthcare administrator and specialist.' },
    { name: 'Katie Park', bio: 'Hospitality management expert and intro to marketing specialist.' },
    { name: 'Anuva Shrestha', bio: 'Hospitality management expert and organizer.' },
    { name: 'Rebecca Li', bio: 'Hospitality management expert and intro to business presenter.' },
    { name: 'Aarav Mohindra', bio: 'Hospitality management expert and strategist.' },
    { name: 'Samiksha Anchuri', bio: 'Hospitality management expert and sports management strategist.' },
    { name: 'Neev Popli', bio: 'Hospitality management expert and public speaker.' },
    { name: 'Prisha Mundra', bio: 'Hospitality management expert and parliamentary procedure specialist.' },
    { name: 'Harp Brar', bio: 'Hospitality management expert and parliamentary procedure specialist.' },
    { name: 'Joshua Yeo', bio: 'Hospitality management expert and social media strategist.' },
    { name: 'Caleb Yeo', bio: 'Hospitality management expert and parliamentary procedure specialist.' },
    { name: 'Edward Zhang', bio: 'Hospitality management expert and marketing strategist.' },
    { name: 'Pariza Nizam', bio: 'Human resources advocate and organizational leader.' },
    { name: 'Eliana Chung', bio: 'Human resources advocate and marketing expert.' },
    { name: 'Shruti Vinodkumar', bio: 'Human resources advocate and parliamentary procedure expert.' },
    { name: 'Aiden Silva', bio: 'Impromptu speaker and intro to public speaker.' },
    { name: 'Ronak Singh', bio: 'Impromptu speaker and parliamentary procedure expert.' },
    { name: 'Bhadra Pillai', bio: 'Impromptu speaker and communicator.' },
    { name: 'Abhay Sankar', bio: 'Impromptu speaker and public speaker.' },
    { name: 'Ibrahim Ansari', bio: 'Impromptu speaker and parliamentary procedure expert.' },
    { name: 'Ishaan Sharma', bio: 'Insurance expert and risk manager.' },
    { name: 'Vivaan Singh', bio: 'Insurance expert and intro to business communicator.' },
    { name: 'Charik Malik', bio: 'Insurance expert and project manager.' },
    { name: 'Manvik Madupuru', bio: 'International business strategist and job interview expert.' },
    { name: 'Mehar Uppal', bio: 'International business strategist and marketing expert.' },
    { name: 'Ayushi Malla', bio: 'International business strategist and intro to public speaker.' },
    { name: 'Arul Saravanan', bio: 'International business strategist and intro to business presenter.' },
    { name: 'Niyati Rao', bio: 'Intro to business communicator and intro to social media strategist.' },
    { name: 'Dhriti Baireddy', bio: 'Intro to business communicator and intro to public speaker.' },
    { name: 'Nishka Bansal', bio: 'Intro to business communicator and intro to business procedures expert.' },
    { name: 'Vaibhu Lakkakula', bio: 'Intro to business concepts expert and network designer.' },
    { name: 'Kanak Aggarwal', bio: 'Intro to business concepts expert and marketing strategist.' },
    { name: 'Tanvi Kadiyala', bio: 'Intro to business concepts expert and intro to business presenter.' },
    { name: 'Ronin Issa', bio: 'Intro to business concepts expert and learner.' },
    { name: 'Krithikha Bharathy', bio: 'Intro to business presenter and collaborator.' },
    { name: 'Kavya Seshan', bio: 'Intro to business presenter and team player.' },
    { name: 'Vedant Gopalan', bio: 'Intro to business presenter and intro to programmer.' },
    { name: 'Jerry Qu', bio: 'Intro to business presenter and intro to public speaker.' },
    { name: 'Vanshi Patel', bio: 'Intro to business presenter and intro to social media strategist.' },
    { name: 'Vera Heng', bio: 'Intro to business presenter and organizer.' },
    { name: 'Maithili Nadig', bio: 'Intro to business presenter and intro to social media strategist.' },
    { name: 'Sahithya Vellanki', bio: 'Intro to business presenter and collaborator.' },
    { name: 'Tanirika Koka', bio: 'Intro to business presenter and intro to social media strategist.' },
    { name: 'Aarna Vinay', bio: 'Intro to business presenter and team player.' },
    { name: 'Riya Ageeru', bio: 'Intro to business presenter and collaborator.' },
    { name: 'Saanvi Sahoo', bio: 'Intro to business presenter and team player.' },
    { name: 'Keely Fan', bio: 'Intro to business presenter and organizer.' },
    { name: 'Nikhil Tummapudi', bio: 'Intro to business presenter and collaborator.' },
    { name: 'Siddhanth Maurya', bio: 'Intro to business presenter and team player.' },
    { name: 'Aarush Shinu', bio: 'Intro to business presenter and learner.' },
    { name: 'Rehan Shaikh', bio: 'Intro to business presenter and collaborator.' },
    { name: 'Adhyan Rangole', bio: 'Intro to business presenter and team player.' },
    { name: 'Sammith Kuluru', bio: 'Intro to business presenter and learner.' },
    { name: 'Sankeerth Vallapureddy', bio: 'Intro to business presenter and intro to business procedures expert.' },
    { name: 'Pranav Sharma', bio: 'Intro to business procedures expert and intro to public speaker.' },
    { name: 'Ishita Ponnaganti', bio: 'Intro to business procedures expert and visual designer.' },
    { name: 'Akshita Burra', bio: 'Intro to FBLA expert and sports management strategist.' },
    { name: 'Akshat Kumar', bio: 'Intro to FBLA expert and job interview specialist.' },
    { name: 'Yatee Makadia', bio: 'Intro to FBLA expert and learner.' },
    { name: 'Aarav Marok', bio: 'Intro to FBLA expert and intro to retail specialist.' },
    { name: 'Aarav Sharma', bio: 'Intro to IT expert and intro to programmer.' },
    { name: 'Anika Sharma', bio: 'Intro to IT expert and sales presenter.' },
    { name: 'Adhu Manikandan', bio: 'Intro to IT expert and tech enthusiast.' },
    { name: 'Shresta Srinivasa', bio: 'Intro to IT expert and intro to programmer.' },
    { name: 'Suluv Vaish', bio: 'Intro to IT expert and intro to public speaker.' },
    { name: 'Arnav Singh', bio: 'Intro to marketing expert and intro to social media strategist.' },
    { name: 'Lasya Vadakuppa', bio: 'Intro to marketing expert and sales presenter.' },
    { name: 'Amy Deepu', bio: 'Intro to marketing expert and intro to social media strategist.' },
    { name: 'Diya Patel', bio: 'Intro to parliamentary procedure expert and public service announcer.' },
    { name: 'Akshaya Nandigama', bio: 'Intro to programmer and coder.' },
    { name: 'Tanisha Shankpal', bio: 'Intro to programmer and network designer.' },
    { name: 'Yo-Cheng Liao', bio: 'Intro to programmer and management information systems expert.' },
    { name: 'Reyansh Kuntawar', bio: 'Intro to programmer and intro to social media strategist.' },
    { name: 'Rishi Kumpatla', bio: 'Intro to programmer and sales presenter.' },
    { name: 'Samick Churi', bio: 'Intro to public speaker and intro to business presenter.' },
    { name: 'Rajit Sen', bio: 'Intro to public speaker and retail management expert.' },
    { name: 'Angelina Samuel', bio: 'Intro to public speaker and communicator.' },
    { name: 'Lalith Senthil', bio: 'Intro to retail specialist and mobile app developer.' },
    { name: 'Reyansh Kuntawar', bio: 'Intro to social media strategist and intro to programmer.' },
    { name: 'Connor Huang', bio: 'Intro to social media strategist and parliamentary procedure expert.' },
    { name: 'Nita Swadesh', bio: 'Intro to social media strategist and collaborator.' },
    { name: 'Atishay Gupta', bio: 'Intro to social media strategist and supply chain manager.' },
    { name: 'Micah Park', bio: 'Intro to social media strategist and supply chain manager.' },
    { name: 'Muskaan Mathur', bio: 'Intro to social media strategist and content creator.' },
    { name: 'Evelyn Lee', bio: 'Intro to social media strategist and organizer.' },
    { name: 'Chloe Kao', bio: 'Intro to social media strategist and team player.' },
    { name: 'Meenakshi Eashwar', bio: 'Intro to social media strategist and public speaker.' },
    { name: 'Amogh Murthy', bio: 'Intro to social media strategist and collaborator.' },
    { name: 'Maaya Ramesh', bio: 'Intro to social media strategist and content creator.' },
    { name: 'Shayantam Singh', bio: 'Intro to social media strategist and team player.' },
    { name: 'Aarin Hatkhamkar', bio: 'Intro to social media strategist and organizer.' },
    { name: 'Priyanna Naicker', bio: 'Intro to social media strategist and collaborator.' },
    { name: 'Nikhita Panja', bio: 'Intro to social media strategist and team player.' },
    { name: 'Manish Vishnuram', bio: 'Intro to supply chain expert and supply chain manager.' },
    { name: 'Akshaini Yanamandra', bio: 'Intro to supply chain expert and analyst.' },
    { name: 'Kayla Phan', bio: 'Intro to supply chain expert and securities analyst.' },
    { name: 'Namya Thareja', bio: 'Intro to supply chain expert and organizer.' },
    { name: 'Aditya Chattopadhyay', bio: 'Intro to supply chain expert and analyst.' },
    { name: 'Prakruthi Venugopalan', bio: 'Job interview expert and website designer.' },
    { name: 'Calvin Widjaja', bio: 'Job interview expert and project manager.' },
    { name: 'Arham Tanweer', bio: 'Journalism expert and public administration specialist.' },
    { name: 'Advaith Voodem', bio: 'Management information systems expert and parliamentary procedure specialist.' },
    { name: 'Rishi Khante', bio: 'Management information systems expert and network designer.' },
    { name: 'Aanya Rawal', bio: 'Management information systems expert and website coder.' },
    { name: 'Andy Zhang', bio: 'Management information systems expert and strategist.' },
    { name: 'Aadhya Goyal', bio: 'Management information systems expert and website coder.' },
    { name: 'Alisha Verma', bio: 'Marketing expert and visual designer.' },
    { name: 'Minh Nguyen', bio: 'Marketing expert and parliamentary procedure specialist.' },
    { name: 'Nivedita Saju Menon', bio: 'Marketing expert and parliamentary procedure specialist.' },
    { name: 'Samhith Kotapalle', bio: 'Marketing expert and sales presenter.' },
    { name: 'Ritvik Bansal', bio: 'Mobile app developer and parliamentary procedure expert.' },
    { name: 'Satwik Mannepalli', bio: 'Mobile app developer and technology support specialist.' },
    { name: 'Gordon Zhang', bio: 'Mobile app developer and network designer.' },
    { name: 'Anvith Neelam', bio: 'Network designer and website coder.' },
    { name: 'Sybe Hofman', bio: 'Networking infrastructures expert and website coder.' },
    { name: 'Siyona Sharma', bio: 'Organizational leader and sales presenter.' },
    { name: 'Samya Sharma', bio: 'Parliamentary procedure expert and supply chain manager.' },
    { name: 'Aneri Bhatt', bio: 'Parliamentary procedure expert and supply chain manager.' },
    { name: 'Anagha Krishna', bio: 'Parliamentary procedure expert and supply chain manager.' },
    { name: 'Pakhi Saini', bio: 'Parliamentary procedure expert and supply chain manager.' },
    { name: 'Joshitha Velmuragan', bio: 'Parliamentary procedure expert and public administration specialist.' },
    { name: 'Navkiran Kaur', bio: 'Parliamentary procedure expert and team player.' },
    { name: 'Noorpreet Kaur', bio: 'Parliamentary procedure expert and collaborator.' },
    { name: 'Manu Nellapalle', bio: 'Parliamentary procedure expert and team player.' },
    { name: 'Joseph Seong', bio: 'Parliamentary procedure expert and collaborator.' },
    { name: 'Elijah Lee', bio: 'Parliamentary procedure expert and retail management specialist.' },
    { name: 'Siddarth Saravananm', bio: 'Personal finance expert and analyst.' },
    { name: 'Ekansh Sen', bio: 'Personal finance expert and real estate specialist.' },
    { name: 'Devin Shao', bio: 'Personal finance expert and securities analyst.' },
    { name: 'Shreya Sharma', bio: 'Project manager and sales presenter.' },
    { name: 'Gargi Sahoo', bio: 'Project manager and securities analyst.' },
    { name: 'Rigel Starks', bio: 'Project manager and strategist.' },
    { name: 'Alaina Kim', bio: 'Public service announcer and advocate.' },
    { name: 'Aditi Sehgal', bio: 'Public service announcer and communicator.' },
    { name: 'Marniaa Shruti', bio: 'Public service announcer and team player.' },
    { name: 'Ahana Ghatuparthi', bio: 'Public service announcer and advocate.' },
    { name: 'Ivana Philip', bio: 'Public service announcer and communicator.' },
    { name: 'Shijumita Kumar', bio: 'Public speaker and sales presenter.' },
    { name: 'Sahib baidwan', bio: 'Real estate expert and investor.' },
    { name: 'Pranil shukla', bio: 'Real estate expert and analyst.' },
    { name: 'Muskan Sandhu', bio: 'Retail management expert and social media strategist.' },
    { name: 'Aaditya Perianna', bio: 'Retail management expert and specialist.' },
    { name: 'Shaurya Sahdev', bio: 'Sales presenter and website coder.' },
    { name: 'Rithwik Rajashekara', bio: 'Sales presenter and website designer.' },
    { name: 'Srihan Prasanna', bio: 'Sales presenter and technology support specialist.' },
    { name: 'Aarish Kumar', bio: 'Securities analyst and website designer.' },
    { name: 'Bharvi Doshi', bio: 'Social media strategist and content creator.' },
    { name: 'Samshi Chinthireddy', bio: 'Social media strategist and supply chain manager.' },
    { name: 'Dhriti Burugupalli', bio: 'Social media strategist and supply chain manager.' },
    { name: 'Harshi Abburi', bio: 'Social media strategist and website designer.' },
    { name: 'Ganishka Kuntumalla', bio: 'Social media strategist and sports management expert.' },
    { name: 'Krithi Grandhe', bio: 'Sports management expert and visual designer.' },
    { name: 'Anaya Joshi', bio: 'Sports management expert and team player.' },
    { name: 'Jay Thoohan', bio: 'Sports management expert and strategist.' },
    { name: 'Chandan Chengalvala', bio: 'Sports management expert and website coder.' },
    { name: 'Viraat Nellutla', bio: 'Technology support specialist and website coder.' },
    { name: 'Sofia Zimbalist', bio: 'Visual designer and creative thinker.' },
    { name: 'Angie Prabhu', bio: 'Visual designer and event planner.' },
    { name: 'Brandon Lin', bio: 'Visual designer and website designer.' },
    { name: 'Rayan Alam', bio: 'Website coder and business planner.' },
    { name: 'Aishwarya Kumaran', bio: 'Website coder and computer problem solver.' },
    { name: 'Rishaan Das', bio: 'Website designer and creative developer.' },
    { name: 'Saatvik Patel', bio: 'Website designer and coder.' },
  ];

  const eventsData = [
    'Accounting', 'Advanced Accounting', 'Advertising', 'Agribusiness', 'Banking and Financial Systems',
    'Broadcast Journalism', 'Business Communication', 'Business Ethics', 'Business Law', 'Business Management',
    'Business Plan', 'Career Portfolio', 'Coding and Programming', 'Computer Applications',
    'Computer Game and Simulation Programming', 'Computer Problem Solving', 'Customer Service', 'Cybersecurity',
    'Data Analysis', 'Data Science & AI', 'Digital Animation', 'Digital Video Production', 'Economics',
    'Entrepreneurship', 'Event Planning', 'Financial Planning', 'Financial Statement Analysis',
    'Future Business Educator', 'Future Business Leader', 'Graphic Design', 'Healthcare Administration',
    'Hospitality and Event Management', 'Human Resources Management', 'Impromptu Speaking',
    'Insurance and Risk Management', 'International Business', 'Intro to Business Communication',
    'Intro to Business Concepts', 'Intro to Business Presentation', 'Intro to Business Procedures',
    'Intro to FBLA', 'Intro to Information Technology', 'Intro to Marketing Concepts',
    'Intro to Parliamentary Procedure', 'Intro to Programming', 'Intro to Public Speaking',
    'Intro to Retail and Merchandising', 'Intro to Social Media Strategy', 'Intro to Supply Chain Management',
    'Job Interview', 'Journalism', 'Management Information Systems', 'Marketing', 'Mobile App Development',
    'Network Design', 'Networking Infrastructures', 'Organizational Leadership', 'Parliamentary Procedure',
    'Personal Finance', 'Project Management', 'Public Administration and Management', 'Public Service Announcement',
    'Public Speaking', 'Real Estate', 'Retail Management', 'Sales Presentation', 'Securities and Investments',
    'Social Media Strategies', 'Sports and Entertainment Management', 'Supply Chain Management',
    'Technology Support Services', 'Visual Design', 'Website Coding and Development', 'Website Design',
  ];

  // Insert events
  for (const eventName of eventsData) {
    await db.runAsync('INSERT OR IGNORE INTO events (name) VALUES (?)', [eventName]);
  }

  // Member-Event mappings (based on the provided data)
  const memberEventMappings: { [key: string]: string[] } = {
    'Ashrit Kopparthi': ['Accounting', 'International Business'],
    'Ian Mendonca': ['Accounting', 'Banking and Financial Systems'],
    'Aayush Pant': ['Accounting', 'Coding and Programming'],
    'Atiksh Matharu': ['Accounting', 'Intro to Business Procedures'],
    'Liam Chang': ['Accounting', 'Banking and Financial Systems', 'Supply Chain Management'],
    'Rohaan Pasha': ['Accounting', 'Personal Finance'],
    'Sacchit Boddapati': ['Advanced Accounting', 'Data Science & AI'],
    'Gautham Manigantan': ['Advanced Accounting', 'Coding and Programming'],
    'Niya Aslam': ['Advertising', 'Intro to Marketing Concepts'],
    'Deethya Anuga': ['Advertising', 'Business Plan'],
    'Lucky Kadiam': ['Advertising', 'Sales Presentation'],
    'Vienna Shin': ['Advertising'],
    'Olivia Shin': ['Advertising'],
    'Naman Agrawal': ['Advertising', 'Technology Support Services'],
    'Sprihi Sharma': ['Agribusiness', 'Data Analysis'],
    'Gabrielle Quiere': ['Agribusiness', 'Intro to Business Presentation'],
    'Ashmi Shah': ['Agribusiness', 'Healthcare Administration'],
    'Samhitha Manukonda': ['Banking and Financial Systems', 'Visual Design'],
    'Aman Kolli': ['Banking and Financial Systems', 'Supply Chain Management'],
    'Saipranav Rebala': ['Banking and Financial Systems', 'Supply Chain Management'],
    'Brandon Osckar': ['Banking and Financial Systems', 'Personal Finance'],
    'Sameer Hussaini': ['Banking and Financial Systems', 'Insurance and Risk Management', 'Supply Chain Management'],
    'Shaurya Bansal': ['Banking and Financial Systems', 'Broadcast Journalism'],
    'Arush Rasure': ['Banking and Financial Systems', 'Business Law'],
    'Shikha Prajapati': ['Broadcast Journalism', 'Future Business Educator'],
    'Niteesh AJ': ['Broadcast Journalism'],
    'Aashi Patel': ['Broadcast Journalism', 'Parliamentary Procedure'],
    'Shriya Aroun': ['Broadcast Journalism', 'Parliamentary Procedure'],
    'Rachel So': ['Broadcast Journalism', 'Parliamentary Procedure'],
    'Anoushka Haloi': ['Broadcast Journalism', 'Public Service Announcement'],
    'Natalie Ho': ['Broadcast Journalism', 'Intro to Business Presentation'],
    'Saranya Potukuchi': ['Broadcast Journalism', 'Public Service Announcement'],
    'Varalika Konduri': ['Broadcast Journalism'],
    'Saiprajna Ravooru': ['Broadcast Journalism', 'Public Speaking'],
    'Shrita Kopparthi': ['Broadcast Journalism', 'Business Communication'],
    'Ved Dalvi': ['Broadcast Journalism', 'Intro to Business Procedures'],
    'Varun Patwardhan': ['Broadcast Journalism'],
    'Rafail Popa': ['Broadcast Journalism', 'Business Management'],
    'Khushi Bhimani': ['Broadcast Journalism', 'Job Interview'],
    'Anna Abraham': ['Broadcast Journalism', 'Financial Planning'],
    'Kriyan Krishnan': ['Business Communication', 'Digital Video Production'],
    'Sahana Singh': ['Business Communication', 'Retail Management'],
    'Rohil Varshney': ['Business Communication', 'Digital Video Production'],
    'Iman Siddiqui': ['Business Communication', 'Sales Presentation'],
    'Nitya Anand': ['Business Communication', 'Journalism'],
    'Amr Omar': ['Business Ethics'],
    'Muhammad Koul': ['Business Ethics'],
    'Adam Alaruri': ['Business Ethics', 'Healthcare Administration'],
    'Kashvi Arora': ['Business Ethics', 'Organizational Leadership'],
    'Ananya Mallick': ['Business Ethics', 'Event Planning'],
    'Shrita Palla': ['Business Ethics', 'Business Law'],
    'Snigdha Sri Garlapati': ['Business Ethics', 'Financial Statement Analysis'],
    'Ellisandra Sou': ['Business Ethics'],
    'Tanvi Kuttuva': ['Business Ethics', 'Intro to Business Communication'],
    'Aashini Ramesh': ['Business Ethics'],
    'Swarali Karale': ['Business Ethics', 'Website Design'],
    'Srianvika Siram': ['Business Ethics', 'Business Plan'],
    'Puranjay Wadhawan': ['Business Law'],
    'Gayathri Priya Balla': ['Business Law', 'Journalism'],
    'Swati Premkumar': ['Business Law'],
    'Saanvi Lankalapalli': ['Business Law', 'Intro to Parliamentary Procedure'],
    'Aahna Dattkaya': ['Business Law', 'Intro to Retail and Merchandising'],
    'Ayla Tamber': ['Business Management', 'Event Planning'],
    'Keerth Kotha': ['Business Management', 'Intro to Business Concepts'],
    'Amogh Jain': ['Business Management', 'Website Design'],
    'Rajeev Kalagara': ['Business Management'],
    'Nella Sharma': ['Business Management', 'Customer Service'],
    'Amreen Dadwal': ['Business Management', 'Real Estate'],
    'Elizabeth Tselyuk': ['Business Management', 'Intro to Business Presentation'],
    'Sashvitha Poobalan': ['Business Management', 'Social Media Strategies'],
    'Isabella Salazar': ['Business Management', 'Social Media Strategies'],
    'Abhi Kaki': ['Business Management'],
    'Hei kan Tang': ['Business Management'],
    'Arnav Verma': ['Business Management'],
    'Vihaan Singh': ['Business Plan', 'Data Analysis', 'Intro to Business Communication'],
    'Ruhaan Sidhu': ['Business Plan', 'Data Analysis'],
    'Rayan Alam': ['Business Plan', 'Website Coding and Development'],
    'Anushree Gupta': ['Business Plan', 'Social Media Strategies'],
    'Vilina Pai': ['Business Plan', 'Human Resources Management'],
    'Tanisha Chandel': ['Business Plan', 'Graphic Design'],
    'Tanishka Yella': ['Business Plan', 'Graphic Design'],
    'Avantika Santhosh': ['Business Plan'],
    'Prisha Sharma': ['Business Plan', 'Data Science & AI'],
    'Ayush Balwalli': ['Business Plan', 'Sports and Entertainment Management'],
    'Kailani Fisher': ['Business Plan', 'Sports and Entertainment Management'],
    'Shahaan Dhebar': ['Business Plan', 'Entrepreneurship'],
    'Aaric Das': ['Business Plan'],
    'Aarav Verma': ['Business Plan'],
    'Satvik Tadiparti': ['Business Plan', 'Intro to Retail and Merchandising'],
    'Sneha Nandkeolyar': ['Career Portfolio', 'Entrepreneurship'],
    'Geethika Chandolu': ['Career Portfolio', 'Social Media Strategies'],
    'Saswathy Srishankar': ['Career Portfolio', 'Job Interview'],
    'Jahnavi Shukla': ['Career Portfolio'],
    'Ali Mirza': ['Career Portfolio', 'Intro to Public Speaking'],
    'Alisa Kyrychenko': ['Career Portfolio', 'Website Coding and Development'],
    'Aadit Aggarwal': ['Coding and Programming', 'Mobile App Development'],
    'Rithvika Devisetti': ['Coding and Programming', 'Website Coding and Development'],
    'Sayesha Rajbhandari': ['Coding and Programming', 'Website Coding and Development'],
    'Gagana Rudra Bodala': ['Coding and Programming', 'Website Coding and Development'],
    'Matthew Kokhan': ['Computer Game and Simulation Programming', 'Graphic Design'],
    'Eric Luo': ['Computer Game and Simulation Programming', 'Graphic Design'],
    'Srivats Iyer': ['Computer Game and Simulation Programming'],
    'Aryaman Rao': ['Computer Game and Simulation Programming', 'Supply Chain Management'],
    'Abhinav Iyer': ['Computer Game and Simulation Programming', 'Insurance and Risk Management'],
    'Dhanuh Bogam': ['Computer Game and Simulation Programming', 'Cybersecurity'],
    'Elina Shah': ['Computer Game and Simulation Programming', 'Intro to Programming'],
    'Ashrita Saravanan Vaishnavi': ['Computer Game and Simulation Programming', 'Cybersecurity'],
    'Sarthak Kansal': ['Computer Applications', 'Intro to Business Communication'],
    'Riddhesh Jaini': ['Computer Applications', 'Intro to Supply Chain Management'],
    'Anvi Dua': ['Computer Applications', 'Website Coding and Development'],
    'Aishwarya Kumaran': ['Computer Problem Solving', 'Website Coding and Development'],
    'Mahima Iyer': ['Computer Problem Solving', 'Future Business Leader'],
    'Shubh Parihar': ['Computer Problem Solving', 'Data Science & AI'],
    'Akshar Parmar': ['Computer Problem Solving', 'Website Design'],
    'Aditi Kesarwani': ['Computer Problem Solving', 'Event Planning'],
    'Ryan Cutinha': ['Computer Problem Solving', 'Networking Infrastructures'],
    'Ryan Wang': ['Computer Problem Solving', 'Mobile App Development'],
    'Meera Bhise': ['Customer Service', 'Sports and Entertainment Management'],
    'Maitree Chauhan': ['Customer Service', 'Human Resources Management'],
    'Megan Song': ['Customer Service', 'Marketing'],
    'Sarah Chung': ['Customer Service', 'Impromptu Speaking'],
    'Krish Shah': ['Customer Service', 'Intro to Marketing Concepts'],
    'Aanya Sheth': ['Customer Service', 'Event Planning'],
    'Feven Bizuayehu': ['Cybersecurity', 'Data Analysis'],
    'Yusuf Abbasi': ['Cybersecurity', 'Website Design'],
    'Ayla Mir': ['Cybersecurity', 'Data Analysis'],
    'Adyan Ali': ['Cybersecurity', 'Sales Presentation'],
    'Mikul Pasupathi': ['Cybersecurity', 'Intro to Business Presentation'],
    'Vivaan Pole': ['Cybersecurity', 'Intro to Social Media Strategy'],
    'Yuvin Agrawal': ['Cybersecurity', 'Data Science & AI'],
    'Shaurya Gera': ['Data Analysis', 'Data Science & AI'],
    'Sreshta Namala': ['Data Analysis', 'Public Speaking'],
    'Vanshika Kalluri': ['Data Analysis', 'Hospitality and Event Management'],
    'Nishtha Priya': ['Data Analysis', 'Networking Infrastructures'],
    'Pushkal Kumar': ['Data Analysis', 'Mobile App Development'],
    'Guhan Thiagarajan': ['Data Analysis', 'Networking Infrastructures'],
    'Sujan Saravanan': ['Data Analysis', 'Intro to Business Presentation'],
    'Sidharth Vellanki': ['Data Analysis', 'Network Design'],
    'Abhinav Bonagiri': ['Data Analysis', 'Network Design'],
    'Saravana Jayavelu': ['Data Analysis', 'Sports and Entertainment Management'],
    'Venkat Chandra': ['Data Analysis', 'Future Business Leader'],
    'Neel Patel': ['Data Analysis', 'Future Business Leader'],
    'Fiona Au': ['Data Analysis', 'Public Service Announcement'],
    'Ronit Agarwal': ['Data Science & AI', 'Website Coding and Development'],
    'Satya Tumuluri': ['Data Science & AI', 'Economics'],
    'Vyom Joshi': ['Data Science & AI', 'Financial Planning'],
    'Vidhyuth Rajesh Kanna': ['Data Science & AI', 'Economics'],
    'Shreya Battula': ['Data Science & AI', 'Intro to Programming'],
    'Shaaz Alicherry': ['Data Science & AI', 'International Business'],
    'Devansh Ahuja': ['Data Science & AI', 'Intro to Business Presentation'],
    'Rithwik Bhimanadhuni': ['Data Science & AI', 'Digital Video Production'],
    'Gyandeep Kintali': ['Data Science & AI'],
    'Avisha Agrawal': ['Digital Animation', 'Intro to Information Technology'],
    'Disha Pudakar': ['Digital Animation'],
    'Saisha Agarwal': ['Digital Animation', 'Intro to Parliamentary Procedure'],
    'Oviya Raja': ['Digital Animation', 'Healthcare Administration'],
    'Arian Khaire': ['Digital Animation', 'Sports and Entertainment Management'],
    'Krishna Chintalapati': ['Digital Animation', 'Hospitality and Event Management'],
    'Mikail Ahmed': ['Digital Animation', 'Personal Finance'],
    'Ishaan Agarwal': ['Digital Animation', 'Website Design'],
    'Kavya Subramanian': ['Digital Video Production', 'Sales Presentation'],
    'tarinika prasath': ['Digital Video Production', 'Securities and Investments'],
    'Saptaparna Dey': ['Digital Video Production'],
    'Joel Bijoy': ['Digital Video Production', 'Website Coding and Development'],
    'Rishik Birru': ['Digital Video Production', 'Website Coding and Development'],
    'Pranav Saravanan': ['Digital Video Production', 'Financial Statement Analysis'],
    'Benjamin Xavier': ['Digital Video Production', 'Future Business Educator'],
    'Marcus Balauag': ['Digital Video Production', 'Financial Statement Analysis'],
    'Keyan Shah': ['Digital Video Production', 'Mobile App Development'],
    'Aadhav Iyer': ['Digital Video Production'],
    'Max Trepp': ['Digital Video Production'],
    'Pratyush Patnaik': ['Digital Video Production', 'Insurance and Risk Management'],
    'Tasmia Minhaz': ['Economics', 'Graphic Design'],
    'Anisha Datta': ['Economics', 'Financial Statement Analysis'],
    'Rayan Aziz': ['Economics', 'Personal Finance'],
    'Nathan Dusapin': ['Economics', 'Personal Finance'],
    'Saahithi Mamillapalli': ['Entrepreneurship', 'Marketing'],
    'Julian Sieu': ['Entrepreneurship', 'Sales Presentation'],
    'Ajay Joshi': ['Entrepreneurship', 'Intro to Parliamentary Procedure'],
    'Aniruddh Gatla': ['Entrepreneurship', 'International Business'],
    'Om Kharade': ['Entrepreneurship', 'Intro to Business Presentation'],
    'Kobee Tan': ['Entrepreneurship'],
    'Elisha Kim': ['Event Planning', 'Intro to Marketing Concepts'],
    'Sabrina Castellanos French': ['Event Planning'],
    'Sinchana Vivek': ['Event Planning', 'Sales Presentation'],
    'Dhatri Achyutha': ['Event Planning', 'Healthcare Administration'],
    'Nayana Surisetti': ['Event Planning', 'Intro to Social Media Strategy'],
    'Varenya Pothukuchi': ['Event Planning', 'Visual Design'],
    'Yasha Gatla': ['Event Planning', 'International Business'],
    'Srianshi Samantaray': ['Event Planning', 'Financial Planning'],
    'Rithika Pooboni': ['Event Planning', 'Graphic Design'],
    'Quinlan Pradana': ['Event Planning'],
    'Aarav Patil': ['Event Planning', 'Sports and Entertainment Management'],
    'Vamika Putane': ['Event Planning'],
    'Samvit Nadgouda': ['Event Planning', 'Intro to FBLA'],
    'Aileen Putla': ['Event Planning', 'Website Design'],
    'Ritul Dwivedi': ['Event Planning', 'Public Speaking'],
    'Sahana Senthilkumar': ['Event Planning', 'Visual Design'],
    'Angelika Prabhu': ['Event Planning', 'Visual Design'],
    'Sarah John': ['Event Planning', 'Social Media Strategies'],
    'Andrea Chalissery': ['Event Planning', 'Intro to Business Concepts'],
    'Komalika Mamidi': ['Financial Planning', 'Intro to Business Presentation'],
    'Nandini Komma': ['Financial Planning', 'Intro to Business Presentation'],
    'Samhitha Nekkanty': ['Financial Planning', 'Social Media Strategies'],
    'Joshita Munnangi': ['Financial Planning', 'Social Media Strategies'],
    'Anshi Mehta': ['Financial Planning', 'Social Media Strategies'],
    'Devansh Agarwal': ['Financial Planning', 'Intro to Programming'],
    'Aiden Sol': ['Financial Planning', 'Social Media Strategies'],
    'Nathan Son': ['Financial Planning', 'Social Media Strategies'],
    'Jeffrey Jiang': ['Financial Planning', 'Personal Finance'],
    'Advaith Koushik': ['Financial Statement Analysis', 'Intro to Programming'],
    'Anay Arya': ['Financial Statement Analysis', 'Network Design'],
    'Nishad Satghare': ['Financial Statement Analysis', 'Network Design'],
    'Matthew Song': ['Financial Statement Analysis', 'Network Design'],
    'Jaithra Putane': ['Financial Statement Analysis', 'Public Service Announcement'],
    'Sarayu Nukala': ['Financial Statement Analysis', 'Mobile App Development'],
    'Sanskriti Shukla': ['Financial Statement Analysis', 'Public Administration and Management'],
    'Anusha Date': ['Financial Statement Analysis', 'Supply Chain Management'],
    'Rishitha Sindogi': ['Future Business Educator', 'Parliamentary Procedure'],
    'Sara Kansal': ['Future Business Educator', 'Social Media Strategies'],
    'Anaya Borade': ['Future Business Educator', 'Project Management'],
    'Kelly Mascarenhas': ['Future Business Educator', 'Sports and Entertainment Management'],
    'Ishaan Regalla': ['Future Business Leader', 'Real Estate'],
    'Aradhna Praveen': ['Future Business Leader', 'Social Media Strategies'],
    'Mahi Parikh': ['Graphic Design', 'Securities and Investments'],
    'Saanvi Vijayvargiya': ['Graphic Design', 'Visual Design'],
    'Ananya Gupta': ['Graphic Design', 'International Business'],
    'Tej Simha Tummapudi': ['Graphic Design', 'Website Coding and Development'],
    'Kody Choi': ['Graphic Design', 'Public Service Announcement'],
    'Gianna Canos': ['Graphic Design', 'Parliamentary Procedure'],
    'Sankari Kk': ['Graphic Design', 'Public Speaking'],
    'Ajooni Dhanoa': ['Graphic Design', 'Visual Design'],
    'Andy Yang': ['Graphic Design', 'Website Design'],
    'Soumil Pole': ['Graphic Design', 'Website Design'],
    'Avni Panchal': ['Graphic Design', 'Visual Design'],
    'Kavya Mohanasundaram': ['Graphic Design', 'Visual Design'],
    'Yunhan Li': ['Graphic Design', 'Website Design'],
    'Sanjana Krishnan': ['Healthcare Administration', 'Social Media Strategies'],
    'Srinath Vemula': ['Healthcare Administration', 'Real Estate'],
    'Ellena Wong': ['Healthcare Administration', 'Human Resources Management'],
    'Shravya More': ['Healthcare Administration', 'Social Media Strategies'],
    'Laya Mohan': ['Healthcare Administration'],
    'Katie Park': ['Hospitality and Event Management', 'Intro to Marketing Concepts'],
    'Anuva Shrestha': ['Hospitality and Event Management'],
    'Rebecca Li': ['Hospitality and Event Management', 'Intro to Business Presentation'],
    'Aarav Mohindra': ['Hospitality and Event Management'],
    'Samiksha Anchuri': ['Hospitality and Event Management', 'Sports and Entertainment Management'],
    'Neev Popli': ['Hospitality and Event Management', 'Public Speaking'],
    'Prisha Mundra': ['Hospitality and Event Management', 'Parliamentary Procedure'],
    'Harp Brar': ['Hospitality and Event Management', 'Parliamentary Procedure'],
    'Joshua Yeo': ['Hospitality and Event Management', 'Social Media Strategies'],
    'Caleb Yeo': ['Hospitality and Event Management', 'Parliamentary Procedure'],
    'Edward Zhang': ['Hospitality and Event Management', 'Marketing'],
    'Pariza Nizam': ['Human Resources Management', 'Organizational Leadership'],
    'Eliana Chung': ['Human Resources Management', 'Marketing'],
    'Shruti Vinodkumar': ['Human Resources Management', 'Parliamentary Procedure'],
    'Aiden Silva': ['Impromptu Speaking', 'Intro to Public Speaking'],
    'Ronak Singh': ['Impromptu Speaking', 'Parliamentary Procedure'],
    'Bhadra Pillai': ['Impromptu Speaking'],
    'Abhay Sankar': ['Impromptu Speaking', 'Public Speaking'],
    'Ibrahim Ansari': ['Impromptu Speaking', 'Parliamentary Procedure'],
    'Ishaan Sharma': ['Insurance and Risk Management'],
    'Vivaan Singh': ['Insurance and Risk Management', 'Intro to Business Communication'],
    'Charik Malik': ['Insurance and Risk Management', 'Project Management'],
    'Manvik Madupuru': ['International Business', 'Job Interview'],
    'Mehar Uppal': ['International Business', 'Marketing'],
    'Ayushi Malla': ['International Business', 'Intro to Public Speaking'],
    'Arul Saravanan': ['International Business', 'Intro to Business Presentation'],
    'Niyati Rao': ['Intro to Business Communication', 'Intro to Social Media Strategy'],
    'Dhriti Baireddy': ['Intro to Business Communication', 'Intro to Public Speaking'],
    'Nishka Bansal': ['Intro to Business Communication', 'Intro to Business Procedures'],
    'Vaibhu Lakkakula': ['Intro to Business Concepts', 'Network Design'],
    'Kanak Aggarwal': ['Intro to Business Concepts', 'Marketing'],
    'Tanvi Kadiyala': ['Intro to Business Concepts', 'Intro to Business Presentation'],
    'Ronin Issa': ['Intro to Business Concepts'],
    'Krithikha Bharathy': ['Intro to Business Presentation'],
    'Kavya Seshan': ['Intro to Business Presentation'],
    'Vedant Gopalan': ['Intro to Business Presentation', 'Intro to Programming'],
    'Jerry Qu': ['Intro to Business Presentation', 'Intro to Public Speaking'],
    'Vanshi Patel': ['Intro to Business Presentation', 'Intro to Social Media Strategy'],
    'Vera Heng': ['Intro to Business Presentation'],
    'Maithili Nadig': ['Intro to Business Presentation', 'Intro to Social Media Strategy'],
    'Sahithya Vellanki': ['Intro to Business Presentation'],
    'Tanirika Koka': ['Intro to Business Presentation', 'Intro to Social Media Strategy'],
    'Aarna Vinay': ['Intro to Business Presentation'],
    'Riya Ageeru': ['Intro to Business Presentation'],
    'Saanvi Sahoo': ['Intro to Business Presentation'],
    'Keely Fan': ['Intro to Business Presentation'],
    'Nikhil Tummapudi': ['Intro to Business Presentation'],
    'Siddhanth Maurya': ['Intro to Business Presentation'],
    'Aarush Shinu': ['Intro to Business Presentation'],
    'Rehan Shaikh': ['Intro to Business Presentation'],
    'Adhyan Rangole': ['Intro to Business Presentation'],
    'Sammith Kuluru': ['Intro to Business Presentation'],
    'Sankeerth Vallapureddy': ['Intro to Business Presentation', 'Intro to Business Procedures'],
    'Pranav Sharma': ['Intro to Business Procedures', 'Intro to Public Speaking'],
    'Ishita Ponnaganti': ['Intro to Business Procedures', 'Visual Design'],
    'Akshita Burra': ['Intro to FBLA', 'Sports and Entertainment Management'],
    'Akshat Kumar': ['Intro to FBLA', 'Job Interview'],
    'Yatee Makadia': ['Intro to FBLA'],
    'Aarav Marok': ['Intro to FBLA', 'Intro to Retail and Merchandising'],
    'Aarav Sharma': ['Intro to Information Technology', 'Intro to Programming'],
    'Anika Sharma': ['Intro to Information Technology', 'Sales Presentation'],
    'Adhu Manikandan': ['Intro to Information Technology'],
    'Shresta Srinivasa': ['Intro to Information Technology', 'Intro to Programming'],
    'Suluv Vaish': ['Intro to Information Technology', 'Intro to Public Speaking'],
    'Arnav Singh': ['Intro to Marketing Concepts', 'Intro to Social Media Strategy'],
    'Lasya Vadakuppa': ['Intro to Marketing Concepts', 'Sales Presentation'],
    'Amy Deepu': ['Intro to Marketing Concepts', 'Intro to Social Media Strategy'],
    'Diya Patel': ['Intro to Parliamentary Procedure', 'Public Service Announcement'],
    'Akshaya Nandigama': ['Intro to Programming'],
    'Tanisha Shankpal': ['Intro to Programming', 'Network Design'],
    'Yo-Cheng Liao': ['Intro to Programming', 'Management Information Systems'],
    'Reyansh Kuntawar': ['Intro to Programming', 'Intro to Social Media Strategy'],
    'Rishi Kumpatla': ['Intro to Programming', 'Sales Presentation'],
    'Samick Churi': ['Intro to Public Speaking', 'Intro to Business Presentation'],
    'Rajit Sen': ['Intro to Public Speaking', 'Retail Management'],
    'Angelina Samuel': ['Intro to Public Speaking'],
    'Lalith Senthil': ['Intro to Retail and Merchandising', 'Mobile App Development'],
    'Connor Huang': ['Intro to Social Media Strategy', 'Parliamentary Procedure'],
    'Nita Swadesh': ['Intro to Social Media Strategy'],
    'Atishay Gupta': ['Intro to Social Media Strategy', 'Supply Chain Management'],
    'Micah Park': ['Intro to Social Media Strategy', 'Supply Chain Management'],
    'Muskaan Mathur': ['Intro to Social Media Strategy'],
    'Evelyn Lee': ['Intro to Social Media Strategy'],
    'Chloe Kao': ['Intro to Social Media Strategy'],
    'Meenakshi Eashwar': ['Intro to Social Media Strategy', 'Public Speaking'],
    'Amogh Murthy': ['Intro to Social Media Strategy'],
    'Maaya Ramesh': ['Intro to Social Media Strategy'],
    'Shayantam Singh': ['Intro to Social Media Strategy'],
    'Aarin Hatkhamkar': ['Intro to Social Media Strategy'],
    'Priyanna Naicker': ['Intro to Social Media Strategy'],
    'Nikhita Panja': ['Intro to Social Media Strategy'],
    'Manish Vishnuram': ['Intro to Supply Chain Management', 'Supply Chain Management'],
    'Akshaini Yanamandra': ['Intro to Supply Chain Management'],
    'Kayla Phan': ['Intro to Supply Chain Management', 'Securities and Investments'],
    'Namya Thareja': ['Intro to Supply Chain Management'],
    'Aditya Chattopadhyay': ['Intro to Supply Chain Management'],
    'Prakruthi Venugopalan': ['Job Interview', 'Website Design'],
    'Calvin Widjaja': ['Job Interview', 'Project Management'],
    'Arham Tanweer': ['Journalism', 'Public Administration and Management'],
    'Advaith Voodem': ['Management Information Systems', 'Parliamentary Procedure'],
    'Rishi Khante': ['Management Information Systems', 'Network Design'],
    'Aanya Rawal': ['Management Information Systems', 'Website Coding and Development'],
    'Andy Zhang': ['Management Information Systems'],
    'Aadhya Goyal': ['Management Information Systems', 'Website Coding and Development'],
    'Alisha Verma': ['Marketing', 'Visual Design'],
    'Minh Nguyen': ['Marketing', 'Parliamentary Procedure'],
    'Nivedita Saju Menon': ['Marketing', 'Parliamentary Procedure'],
    'Samhith Kotapalle': ['Marketing', 'Sales Presentation'],
    'Ritvik Bansal': ['Mobile App Development', 'Parliamentary Procedure'],
    'Satwik Mannepalli': ['Mobile App Development', 'Technology Support Services'],
    'Gordon Zhang': ['Mobile App Development', 'Network Design'],
    'Anvith Neelam': ['Network Design', 'Website Coding and Development'],
    'Sybe Hofman': ['Networking Infrastructures', 'Website Coding and Development'],
    'Siyona Sharma': ['Organizational Leadership', 'Sales Presentation'],
    'Samya Sharma': ['Parliamentary Procedure', 'Supply Chain Management'],
    'Aneri Bhatt': ['Parliamentary Procedure', 'Supply Chain Management'],
    'Anagha Krishna': ['Parliamentary Procedure', 'Supply Chain Management'],
    'Pakhi Saini': ['Parliamentary Procedure', 'Supply Chain Management'],
    'Joshitha Velmuragan': ['Parliamentary Procedure', 'Public Administration and Management'],
    'Navkiran Kaur': ['Parliamentary Procedure'],
    'Noorpreet Kaur': ['Parliamentary Procedure'],
    'Manu Nellapalle': ['Parliamentary Procedure'],
    'Joseph Seong': ['Parliamentary Procedure'],
    'Elijah Lee': ['Parliamentary Procedure', 'Retail Management'],
    'Siddarth Saravananm': ['Personal Finance'],
    'Ekansh Sen': ['Personal Finance', 'Real Estate'],
    'Devin Shao': ['Personal Finance', 'Securities and Investments'],
    'Shreya Sharma': ['Project Management', 'Sales Presentation'],
    'Gargi Sahoo': ['Project Management', 'Securities and Investments'],
    'Rigel Starks': ['Project Management'],
    'Alaina Kim': ['Public Service Announcement'],
    'Aditi Sehgal': ['Public Service Announcement'],
    'Marniaa Shruti': ['Public Service Announcement'],
    'Ahana Ghatuparthi': ['Public Service Announcement'],
    'Ivana Philip': ['Public Service Announcement'],
    'Shijumita Kumar': ['Public Speaking', 'Sales Presentation'],
    'Sahib baidwan': ['Real Estate'],
    'Pranil shukla': ['Real Estate'],
    'Muskan Sandhu': ['Retail Management', 'Social Media Strategies'],
    'Aaditya Perianna': ['Retail Management'],
    'Shaurya Sahdev': ['Sales Presentation', 'Website Coding and Development'],
    'Rithwik Rajashekara': ['Sales Presentation', 'Website Design'],
    'Srihan Prasanna': ['Sales Presentation', 'Technology Support Services'],
    'Aarish Kumar': ['Securities and Investments', 'Website Design'],
    'Bharvi Doshi': ['Social Media Strategies'],
    'Samshi Chinthireddy': ['Social Media Strategies', 'Supply Chain Management'],
    'Dhriti Burugupalli': ['Social Media Strategies', 'Supply Chain Management'],
    'Harshi Abburi': ['Social Media Strategies', 'Website Design'],
    'Ganishka Kuntumalla': ['Social Media Strategies', 'Sports and Entertainment Management'],
    'Krithi Grandhe': ['Sports and Entertainment Management', 'Visual Design'],
    'Anaya Joshi': ['Sports and Entertainment Management'],
    'Jay Thoohan': ['Sports and Entertainment Management'],
    'Chandan Chengalvala': ['Sports and Entertainment Management', 'Website Coding and Development'],
    'Viraat Nellutla': ['Technology Support Services', 'Website Coding and Development'],
    'Sofia Zimbalist': ['Visual Design'],
    'Angie Prabhu': ['Visual Design'],
    'Brandon Lin': ['Visual Design', 'Website Design'],
    'Rishaan Das': ['Website Design'],
    'Saatvik Patel': ['Website Coding and Development', 'Website Design'],
  };

  // Insert members and link to events
  for (const member of membersData) {
    const initials = member.name
      .split(' ')
      .map(n => n[0])
      .join('')
      .toUpperCase();

    const result = await db.runAsync(
      'INSERT INTO members (name, initials, bio) VALUES (?, ?, ?)',
      [member.name, initials, member.bio]
    );

    const memberId = result.lastInsertRowId;
    const events = memberEventMappings[member.name] || [];

    for (const eventName of events) {
      const eventResult = await db.getFirstAsync<{ id: number }>(
        'SELECT id FROM events WHERE name = ?',
        [eventName]
      );

      if (eventResult) {
        await db.runAsync(
          'INSERT INTO member_events (member_id, event_id) VALUES (?, ?)',
          [memberId, eventResult.id]
        );
      }
    }
  }
};

// Get all members with their events
export const getAllMembers = async (): Promise<Member[]> => {
  if (!db) return [];

  const members = await db.getAllAsync<{ id: number; name: string; initials: string; bio: string }>(
    'SELECT * FROM members ORDER BY name'
  );

  const membersWithEvents: Member[] = [];

  for (const member of members) {
    const events = await db.getAllAsync<{ name: string }>(
      `SELECT e.name 
       FROM events e 
       JOIN member_events me ON e.id = me.event_id 
       WHERE me.member_id = ?`,
      [member.id]
    );

    membersWithEvents.push({
      ...member,
      events: events.map(e => e.name),
    });
  }

  return membersWithEvents;
};

// Search members by name
export const searchMembersByName = async (query: string): Promise<Member[]> => {
  if (!db || !query.trim()) return getAllMembers();

  const members = await db.getAllAsync<{ id: number; name: string; initials: string; bio: string }>(
    'SELECT * FROM members WHERE name LIKE ? ORDER BY name',
    [`%${query}%`]
  );

  const membersWithEvents: Member[] = [];

  for (const member of members) {
    const events = await db.getAllAsync<{ name: string }>(
      `SELECT e.name 
       FROM events e 
       JOIN member_events me ON e.id = me.event_id 
       WHERE me.member_id = ?`,
      [member.id]
    );

    membersWithEvents.push({
      ...member,
      events: events.map(e => e.name),
    });
  }

  return membersWithEvents;
};

// Search members by event
export const searchMembersByEvent = async (eventQuery: string): Promise<{ eventName: string; members: Member[] }[]> => {
  if (!db || !eventQuery.trim()) return [];

  const events = await db.getAllAsync<{ id: number; name: string }>(
    'SELECT * FROM events WHERE name LIKE ? ORDER BY name',
    [`%${eventQuery}%`]
  );

  const results: { eventName: string; members: Member[] }[] = [];

  for (const event of events) {
    const members = await db.getAllAsync<{ id: number; name: string; initials: string; bio: string }>(
      `SELECT m.* 
       FROM members m 
       JOIN member_events me ON m.id = me.member_id 
       WHERE me.event_id = ? 
       ORDER BY m.name`,
      [event.id]
    );

    const membersWithEvents: Member[] = [];

    for (const member of members) {
      const memberEvents = await db.getAllAsync<{ name: string }>(
        `SELECT e.name 
         FROM events e 
         JOIN member_events me ON e.id = me.event_id 
         WHERE me.member_id = ?`,
        [member.id]
      );

      membersWithEvents.push({
        ...member,
        events: memberEvents.map(e => e.name),
      });
    }

    results.push({
      eventName: event.name,
      members: membersWithEvents,
    });
  }

  return results;
};